# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginBackup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 600))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.stackedWidget.setStyleSheet("background-color: #0080ff;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_1 = QtWidgets.QWidget()
        self.pg_1.setObjectName("pg_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.pg_1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.widget = QtWidgets.QWidget(self.pg_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(300, 450))
        self.widget.setMaximumSize(QtCore.QSize(300, 450))
        self.widget.setStyleSheet("background-color:#fff;\n"
"border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.btn_login = QtWidgets.QPushButton(self.widget)
        self.btn_login.setGeometry(QtCore.QRect(110, 370, 75, 30))
        self.btn_login.setMinimumSize(QtCore.QSize(75, 30))
        self.btn_login.setMaximumSize(QtCore.QSize(75, 30))
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("background-color: #0080ff;\n"
"border: none;\n"
"color: white;\n"
"font-size: 13px;")
        self.btn_login.setObjectName("btn_login")
        self.txt_title = QtWidgets.QLabel(self.widget)
        self.txt_title.setGeometry(QtCore.QRect(50, 200, 200, 61))
        self.txt_title.setMinimumSize(QtCore.QSize(200, 61))
        self.txt_title.setMaximumSize(QtCore.QSize(200, 61))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(24)
        self.txt_title.setFont(font)
        self.txt_title.setStyleSheet("color: #636363;")
        self.txt_title.setObjectName("txt_title")
        self.lbl_pass = QtWidgets.QLineEdit(self.widget)
        self.lbl_pass.setGeometry(QtCore.QRect(60, 320, 182, 30))
        self.lbl_pass.setMinimumSize(QtCore.QSize(182, 30))
        self.lbl_pass.setMaximumSize(QtCore.QSize(182, 30))
        self.lbl_pass.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.lbl_pass.setObjectName("lbl_pass")
        self.img_logo = QtWidgets.QLabel(self.widget)
        self.img_logo.setGeometry(QtCore.QRect(80, 30, 140, 140))
        self.img_logo.setMinimumSize(QtCore.QSize(140, 140))
        self.img_logo.setMaximumSize(QtCore.QSize(140, 140))
        self.img_logo.setText("")
        self.img_logo.setPixmap(QtGui.QPixmap("img/slopearth.png"))
        self.img_logo.setScaledContents(True)
        self.img_logo.setObjectName("img_logo")
        self.lbl_user = QtWidgets.QLineEdit(self.widget)
        self.lbl_user.setGeometry(QtCore.QRect(60, 280, 182, 30))
        self.lbl_user.setMinimumSize(QtCore.QSize(182, 30))
        self.lbl_user.setMaximumSize(QtCore.QSize(182, 30))
        self.lbl_user.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.lbl_user.setObjectName("lbl_user")
        self.horizontalLayout_2.addWidget(self.widget)
        self.stackedWidget.addWidget(self.pg_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.page_2)
        self.frame_2.setMinimumSize(QtCore.QSize(338, 582))
        self.frame_2.setMaximumSize(QtCore.QSize(338, 582))
        self.frame_2.setStyleSheet("background-color:#fff;\n"
"border-radius: 10px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setMinimumSize(QtCore.QSize(311, 541))
        self.frame_3.setMaximumSize(QtCore.QSize(311, 541))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_6 = QtWidgets.QLabel(self.frame_3)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.btn_browse3 = QtWidgets.QPushButton(self.frame_3)
        self.btn_browse3.setGeometry(QtCore.QRect(200, 260, 75, 25))
        self.btn_browse3.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_browse3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_browse3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse3.setStyleSheet("background-color: #0080ff;\n"
"color: white;\n"
"border-radius: 5px;")
        self.btn_browse3.setObjectName("btn_browse3")
        self.label_4 = QtWidgets.QLabel(self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(20, 30, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_browse2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_browse2.setGeometry(QtCore.QRect(200, 180, 75, 25))
        self.btn_browse2.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_browse2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_browse2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse2.setStyleSheet("background-color: #0080ff;\n"
"border-radius: 5px;\n"
"color: white;")
        self.btn_browse2.setObjectName("btn_browse2")
        self.cmb_direction = QtWidgets.QComboBox(self.frame_3)
        self.cmb_direction.setGeometry(QtCore.QRect(20, 340, 171, 25))
        self.cmb_direction.setMinimumSize(QtCore.QSize(0, 25))
        self.cmb_direction.setMaximumSize(QtCore.QSize(16777215, 25))
        self.cmb_direction.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.cmb_direction.setObjectName("cmb_direction")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.cmb_direction.addItem("")
        self.btn_calculate = QtWidgets.QPushButton(self.frame_3)
        self.btn_calculate.setGeometry(QtCore.QRect(20, 410, 75, 30))
        self.btn_calculate.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_calculate.setMaximumSize(QtCore.QSize(16777215, 30))
        self.btn_calculate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_calculate.setStyleSheet("background-color: #0080ff;\n"
"border-radius: 5px;\n"
"color: white;\n"
"font-size: 13px;")
        self.btn_calculate.setObjectName("btn_calculate")
        self.lbl_curv = QtWidgets.QLineEdit(self.frame_3)
        self.lbl_curv.setEnabled(False)
        self.lbl_curv.setGeometry(QtCore.QRect(20, 180, 171, 25))
        self.lbl_curv.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_curv.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_curv.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.lbl_curv.setObjectName("lbl_curv")
        self.lbl_route = QtWidgets.QLineEdit(self.frame_3)
        self.lbl_route.setEnabled(False)
        self.lbl_route.setGeometry(QtCore.QRect(20, 260, 171, 25))
        self.lbl_route.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_route.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_route.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.lbl_route.setObjectName("lbl_route")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(20, 230, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 141, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.btn_browse1 = QtWidgets.QPushButton(self.frame_3)
        self.btn_browse1.setGeometry(QtCore.QRect(200, 100, 75, 25))
        self.btn_browse1.setMinimumSize(QtCore.QSize(0, 25))
        self.btn_browse1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.btn_browse1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_browse1.setStyleSheet("background-color: #0080ff;\n"
"border-radius: 5px;\n"
"color: white;")
        self.btn_browse1.setObjectName("btn_browse1")
        self.lbl_design = QtWidgets.QLineEdit(self.frame_3)
        self.lbl_design.setEnabled(False)
        self.lbl_design.setGeometry(QtCore.QRect(20, 100, 171, 25))
        self.lbl_design.setMinimumSize(QtCore.QSize(0, 25))
        self.lbl_design.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lbl_design.setStyleSheet("border-radius: 5px;\n"
"border: 1px solid #d4d4d4;\n"
"background:#f6f6f6;\n"
"color: #0d0d0d;\n"
"padding: 25px 10px;\n"
"text-decoration: none;\n"
"font-size: 14px;\n"
"")
        self.lbl_design.setObjectName("lbl_design")
        self.lbl_message = QtWidgets.QLabel(self.frame_3)
        self.lbl_message.setGeometry(QtCore.QRect(20, 480, 281, 31))
        self.lbl_message.setMinimumSize(QtCore.QSize(281, 31))
        self.lbl_message.setMaximumSize(QtCore.QSize(281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lbl_message.setFont(font)
        self.lbl_message.setText("")
        self.lbl_message.setObjectName("lbl_message")
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setMinimumSize(QtCore.QSize(338, 582))
        self.frame.setMaximumSize(QtCore.QSize(800, 700))
        self.frame.setStyleSheet("background-color: #fff;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mplwidget = MplWidget(self.frame)
        self.mplwidget.setStyleSheet("background:#fff;")
        self.mplwidget.setObjectName("mplwidget")
        self.mplwidget.hide()
        self.verticalLayout_2.addWidget(self.mplwidget)
        self.widget_2 = QtWidgets.QWidget(self.frame)
        self.widget_2.setMinimumSize(QtCore.QSize(318, 50))
        self.widget_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget_2.setStyleSheet("background:#fff;")
        self.widget_2.setObjectName("widget_2")
        self.widget_2.hide()
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_csv = QtWidgets.QPushButton(self.widget_2)
        self.btn_csv.setMinimumSize(QtCore.QSize(147, 30))
        self.btn_csv.setMaximumSize(QtCore.QSize(147, 30))
        self.btn_csv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_csv.setStyleSheet("background-color: #28a745;\n"
"border-radius: 5px;\n"
"color: white;\n"
"font-size: 13px;")
        self.btn_csv.setObjectName("btn_csv")
        self.gridLayout.addWidget(self.btn_csv, 0, 0, 1, 1)
        self.btn_png = QtWidgets.QPushButton(self.widget_2)
        self.btn_png.setMinimumSize(QtCore.QSize(147, 30))
        self.btn_png.setMaximumSize(QtCore.QSize(147, 30))
        self.btn_png.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_png.setStyleSheet("background-color: #dc3545;\n"
"border-radius: 5px;\n"
"color: white;\n"
"font-size: 13px;")
        self.btn_png.setObjectName("btn_png")
        self.gridLayout.addWidget(self.btn_png, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.horizontalLayout.addWidget(self.frame)
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_login.setText(_translate("MainWindow", "Entrar"))
        self.txt_title.setText(_translate("MainWindow", "Inicio de sesión"))
        self.lbl_pass.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.lbl_user.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.label_6.setText(_translate("MainWindow", "Direccion de excavacion:"))
        self.btn_browse3.setText(_translate("MainWindow", "Buscar"))
        self.label_4.setText(_translate("MainWindow", "Archivo de curvas:"))
        self.label.setText(_translate("MainWindow", "Seleccione los archivos:"))
        self.btn_browse2.setText(_translate("MainWindow", "Subir"))
        self.cmb_direction.setItemText(0, _translate("MainWindow", "Norte"))
        self.cmb_direction.setItemText(1, _translate("MainWindow", "Sur"))
        self.cmb_direction.setItemText(2, _translate("MainWindow", "Este"))
        self.cmb_direction.setItemText(3, _translate("MainWindow", "Oeste"))
        self.cmb_direction.setItemText(4, _translate("MainWindow", "Noreste"))
        self.cmb_direction.setItemText(5, _translate("MainWindow", "Sureste"))
        self.cmb_direction.setItemText(6, _translate("MainWindow", "Noroeste"))
        self.cmb_direction.setItemText(7, _translate("MainWindow", "Suroeste"))
        self.btn_calculate.setText(_translate("MainWindow", "Calcular"))
        self.label_5.setText(_translate("MainWindow", "Ruta de descarga:"))
        self.label_3.setText(_translate("MainWindow", "Archivo de diseño:"))
        self.btn_browse1.setText(_translate("MainWindow", "Subir"))
        self.btn_csv.setText(_translate("MainWindow", "CSV"))
        self.btn_png.setText(_translate("MainWindow", "PNG"))
from mplwidget import MplWidget
